# -*- coding: utf-8 -*-
"""task18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16sQKfmWPyZKkyUIOfWCExh5TtSLW8a3l
"""

1.You have a list:
numbers = [5, 2, 9, 1, 5, 6]
Question:
Sort the list in ascending order and remove duplicates.
Expected Output:
[1, 2, 5, 6, 9]

num= [5, 2, 9, 1, 5, 6]
a=[]
for i in num:
  if i not in a:
    a.append(i)
print("after removing the duplicates values",a)
count=len(a)
for i in range(0,count-1+1,1):
  for j in range(0,count-2+1,1):
    if a[j]>a[j+1]:
      temp=a[j]
      a[j]=a[j+1]
      a[j+1]=temp
print("after sorting the list is ",a)

2.write a python program to print the prime numbers form 1 to 100

prime_num=[]
for num in range(1,100+1,1):
  count=0
  for i in range(1,num+1,1):
    if num%i==0:
      count=count+1
  if count==2:
        prime_num.append(num)
print(prime_num)

3.write a python program to check the give year is leap year or not

year=int(input("enter a year "))
if (year%400==0) or (year%4==100 and year%100!=0):
  print(year,"is a leap year")
else:
  print("not a leap year")

4.write a python program to print the numbers from 1 to 100 without using the loops

from ast import Return
def num(n):
  if n>100:
    return
  print(n,end=" ")
  num(n+1)

num(1)